import { describe, expect, it } from 'vitest';
import { generateTypes } from './generate-types.ts';

// Uses quicktype-core from the monorepo/playground node_modules.
// These tests verify the contract: rootTypeName, array wrapping, object naming.

import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '../../');

describe('generateTypes', () => {
  it('object sample → single interface named after typeName', async () => {
    const { declarations, rootTypeName } = await generateTypes(ROOT, {
      typeName: 'GETUserResponse',
      sample: { id: 1, name: 'Alice', email: 'alice@example.com' },
    });

    expect(rootTypeName).toBe('GETUserResponse');
    expect(declarations).toContain('interface GETUserResponse {');
    expect(declarations).toContain('id:');
    expect(declarations).toContain('name:');
    expect(declarations).toContain('email:');
    // No export keyword in declarations
    expect(declarations).not.toMatch(/^export /m);
    // No type alias for a plain object
    expect(declarations).not.toContain('type GETUserResponse');
  });

  it('array sample → item interface + root type alias', async () => {
    const { declarations, rootTypeName } = await generateTypes(ROOT, {
      typeName: 'GETUsersResponse',
      sample: [
        { id: 1, name: 'Alice' },
        { id: 2, name: 'Bob' },
      ],
    });

    expect(rootTypeName).toBe('GETUsersResponse');
    // Item interface declared before the alias
    expect(declarations).toContain('interface GETUsersResponseItem {');
    // Root alias at the end
    expect(declarations).toContain('type GETUsersResponse = GETUsersResponseItem[];');
    const itemIdx = declarations.indexOf('interface GETUsersResponseItem');
    const aliasIdx = declarations.indexOf('type GETUsersResponse');
    expect(itemIdx).toBeLessThan(aliasIdx);
  });

  it('nested object → helper interfaces generated by quicktype', async () => {
    const { declarations, rootTypeName } = await generateTypes(ROOT, {
      typeName: 'GETOrderResponse',
      sample: { id: 1, user: { name: 'Alice', role: 'admin' }, total: 99.5 },
    });

    expect(rootTypeName).toBe('GETOrderResponse');
    expect(declarations).toContain('interface GETOrderResponse {');
    // quicktype generates helper type for the nested `user` object
    expect(declarations).toMatch(/interface \w+/g);
  });

  it('empty array → unknown[] alias, no interfaces', async () => {
    const { declarations, rootTypeName } = await generateTypes(ROOT, {
      typeName: 'GETEmptyResponse',
      sample: [],
    });

    expect(rootTypeName).toBe('GETEmptyResponse');
    expect(declarations).toBe('type GETEmptyResponse = unknown[];');
  });

  it('scalar → simple type alias', async () => {
    const { declarations, rootTypeName } = await generateTypes(ROOT, {
      typeName: 'GETPingResponse',
      sample: 'pong',
    });

    expect(rootTypeName).toBe('GETPingResponse');
    expect(declarations).toBe('type GETPingResponse = string;');
  });

  it('null → null type alias', async () => {
    const { declarations, rootTypeName } = await generateTypes(ROOT, {
      typeName: 'GETNullResponse',
      sample: null,
    });

    expect(rootTypeName).toBe('GETNullResponse');
    expect(declarations).toBe('type GETNullResponse = null;');
  });
});
